labexp/LibreScan

- chdkptp.sh
- renImages.py
Se modificó de modo que quedara más genérico. Ahora los nombres van desde 0 en adelante, sin agregarle ceros de más antes de cada número (Ya no son 0023.jpg).
> Modificacion de archivo rename

- chdkptp.sh
Se agregaron los parámetros en el chdkptp para tomar las fotos bien.
> Modificación del archivo chdkptp.sh - Aumento de tamaño fotos

- main.py
- renImages.py
- rotateImages.py
Including:
-rotate
-rename
-main
> Adding python workflow script

- presentationPrototype/css/index.css
- presentationPrototype/index.html
- Button for create a new project.
- Button to load an old project.
- Both of them responsive and with hover effects.
> Adding buttons to home page

- src/services/utils/outputMaker.py
- src/services/utils/pdfBeads.py
- src/services/utils/scantailor.py
- src/services/utils/task.py
- src/services/utils/taskManager.py
- src/services/utils/tesseract.py
- Task and Outputmaker interfaces.
- Scantailor & Tesseract.
- PDFBeads.
> Adding files for task manager class.

- src/model/camera.py
- src/model/config.py
- src/model/mail.py
- src/model/photo.py
- src/model/project.py
- src/model/projectSummary.py
- src/services/cameraService.py
- src/services/mailService.py
- src/services/projectService.py
- src/services/utils/outputMaker.py
- src/services/utils/pdfBeads.py
- src/services/utils/scantailor.py
- src/services/utils/task.py
- src/services/utils/taskManager.py
- src/services/utils/tesseract.py
- src/services/workFlowService.py
- Standarized code using the snake case used by Python.
- Implemented the make method on PDFBeads utility class.
> Giving snake case standard and PDFBeads util class.

- src/services/utils/outputMaker.py
- src/services/utils/pdfBeads.py
- src/services/utils/task.py
- src/services/workFlowService.py
- Iterating over output maker list and invoking make method to create
the output files.
> Workflow service implentation for finish_product method.

- src/services/utils/scantailor.py
- src/services/utils/taskManager.py
- src/services/utils/tesseract.py
- src/services/workFlowService.py
- Iterating through task list working.
- Generating output (only pdf for now)
> Working in the workflow service and taskmanager class

- src/main.py
- src/model/camera.py
- src/services/cameraService.py
- src/services/utils/chdkptp.py
- src/services/utils/scantailor.py
- src/services/utils/taskManager.py
- While for taking pictures.
- Rotating pictures working, depending on camera orientation.
- Scantailor + tesseract + Pdfbeads working
> Adding main.py

- .gitignore
- src/main.py
- src/services/cameraService.py
- src/services/queueService.py
- src/services/utils/scantailor.py
- src/services/workFlowService.py
Adding service to create threads( by parameter you can set how many (default is 2) ) 
Each thread will process one image ( tiff + hocr ) files generated.
The queue is holding the images id which are able to process
> Adding queueService

- src/services/projectService.py
- It takes as parameter a project object.
- Create configuration files.
> Adding create new project feature:

- src/main.py
- src/services/cameraService.py
- src/services/projectService.py
- src/services/utils/pdfBeads.py
- src/services/utils/scantailor.py
- src/services/utils/taskManager.py
- src/services/utils/tesseract.py
- src/services/workFlowService.py
- Creates processed folder in Project Service.
- Main.py now uses the create project method.
> Spliting project files in raw and proccesed folders

- src/main.py
- src/services/cameraService.py
> Fixing model imports

- src/services/scannerService.py
- src/utils/outputPreparer.py
- src/utils/pdfBeads.py
- src/web/controllers/scannerController.py
- src/web/controllers/taskController.py
- src/web/libreScanWeb.py
- Loop to find picture
- Create .pdf with hocr files. Subprocess command change directory
> Removing rotation error (file not found)

- src/services/scannerService.py
- src/web/assets/css/index.css
- src/web/assets/css/modalPrepareCams.css
- src/web/assets/css/newProject.css
- src/web/assets/js/modalPrepareCams.js
- src/web/assets/js/ocrEditor.js
- src/web/assets/js/scan.js
- src/web/controllers/languageController.py
- src/web/controllers/scannerController.py
- src/web/i18n/locale/spa/LC_MESSAGES/messages.po
- src/web/libreScanWeb.py
- src/web/views/checkOcr.jade
- src/web/views/layouts/modalPrepareCams.jade
- src/web/views/layouts/topbar.jade
- src/web/views/newProject.jade
- src/web/views/scan.jade
- src/web/views/showProjects.jade
- Loading while taking pictures.
- Loading while processing items, it shows how many are left in the queue.
- If capture or recapture fails, the prepare-cams modal is shown.
- Adding messages to provide the user with more info
> Adding loading feature in every page

- src/web/assets/js/ocrEditor.js
- src/web/assets/js/outputPreview.js
- src/web/controllers/scannerController.py
- src/web/controllers/taskController.py
- src/web/libreScanWeb.py
- PDF display working with large files
> Fixing PDF output

- src/utils/chdkptpPT.py
- src/web/assets/js/scan.js
- src/web/controllers/scannerController.py
- Adding raise exception ChdkptpPt
- Removing debug alert web interface
> Fixing status return value

- src/models/photo.py
- src/models/projectPhoto.py
- src/services/hocrService.py
- src/services/imageService.py
- src/services/projectService.py
- src/services/queueService.py
- src/utils/task/taskManager.py
- src/web/controllers/imageController.py
- src/web/controllers/jabiruController.py
- src/web/controllers/scannerController.py
- src/web/controllers/textController.py
- src/web/libreScanWeb.py
Adding Jabiru files and improving queue pictures management
- Adding a new class ProjectPhoto to save the picture working dir and the picture name
- The TaskManager should change in order to load independent project configuration
> Adding Jabiru files

- src/services/hocrService.py
- src/services/imageService.py
- src/services/libhOCR.py
- src/web/assets/css/jabiru.css
- src/web/assets/js/jabiru.js
- src/web/assets/js/ocrEditor.js
- src/web/controllers/imageController.py
- src/web/controllers/jabiruController.py
- src/web/controllers/textController.py
- src/web/libreScanWeb.py
- src/web/views/checkOcr.jade
- src/web/views/jabiru.jade
- The environment variable LS_PROJECT_PATH was fixed
- Library implemented to edit and save hOCR text
- LibreScan workflow was modified to incorporate Jabirú
- Some includes in files were fixed
- tif file parameter name was fixed to be processed as jpg
> Integrate jabiru#7

- src/services/libhOCR.py
- src/web/assets/js/jabiru.js
- Bug in libhOCR while processing hocr files fixed
- Alert in JS eliminated
> Bug fixed in libhOCR

- src/web/i18n/locale/en/LC_MESSAGES/messages.po
- src/web/i18n/locale/gn/LC_MESSAGES/messages.po
- src/web/i18n/locale/pt/LC_MESSAGES/messages.po
- src/web/i18n/locale/spa/LC_MESSAGES/messages.po
- src/web/views/jabiru.jade
jabiru.jade fixed to select dinamically the language
> Messages fixed to each language

- Dockerfile
- docker-compose.yml
- misc/Dependencies.sh
- src/web/libreScanWeb.py
- New docker file
- Restoring local ip to default
- New docker compose file
> Moving LS to Docker

- .gitignore
- README.md
- src/configuration/defaultProjectConfig.yaml
- src/utils/task/impl/scantailor.py
- src/web/assets/js/ocrEditor.js
- src/web/assets/js/scan.js
- Update README.md
- New version-1 to keep updated this version, preparing for version-2 will be on develop branch
- Changing defaultConfig to use layout instead of "l", also add missing `-` to the scantailor option
> Remove extra step ocrEditor
